### PR TITLE
Checklist

### PR DESCRIPTION
**Pull request by jennybc**
As requested in https://github.com/tidyverse/readxl/issues/241#issuecomment-287979857.

I declined to create as an issue or pull request template, because then *every* issue or PR would start with this checklist. Decided `CONTRIBUTING.md` might be the right place? But am not quite sure which file to put this in.

### CODE REVIEW

**Comment by jennybc** [comment]
See also https://github.com/tidyverse/tidytemplate/issues/2

**Comment by hadley** [comment]
Now that http://tidyverse.tidyverse.org exists, maybe this should be an article?

**Comment by hadley** [comment]
OTOH articles probably should live directly under <tidyverse.org>. OTOOH this is a pretty specialised article that's only of use to tidyverse developers

**Comment by hadley** [comment]
Closing in favour of the usethis issue.

**Pull request closed without merging**
