### PR TITLE
update manifesto, linking to programming with dplyr and Advanced R instead of lazyeval

### PR DESCRIPTION
**Pull request by njtierney**
(related to #108)

I thought it might be helpful to link to the "programming with dplyr" vignette and the new section on meta programming in the Advanced R book rather than the lazyeval vignette.

Apologies if I am interrupting things! I realise that there is work going on in describing rlang and tidyevaluation, so please feel free to ignore this :)

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind merge/rebasing? (And removing the spurious roxygen version change)

**Comment by njtierney** [comment]
No problem - how is that? I made the version as `1.2.1.9001` is that OK?

**Comment by hadley** [comment]
Can you please leave the version as is?  And since it's not a user facing change, no need for a news bullet.

**Comment by njtierney** [comment]
No worries - does that look about right?

**Comment by hadley** [comment]
You remove slightly too many zeros 😉

**Comment by njtierney** [comment]
ack!

Howzat?

**Comment by hadley** [comment]
Thanks!

**Comment by njtierney** [comment]
:+1: No problemo

**Pull request merged**
